import { NextResponse } from "next/server";
import { auth } from "@/auth";
// [FIX #3 — critical] This route previously imported the RAW, unscoped
// `prisma` client from "@/lib/db". Per lib/db.ts's own header comment, that
// export is restricted to six narrow, documented categories (registration,
// seed.ts, the authorize() callback, isPlatformAdmin-gated super-admin
// routes, the T4c/fifo.ts shared-transaction-client category, and the
// storefront tenant-by-slug lookup) — this route is none of those. It is
// an ordinary authenticated, tenant-context ADMIN action, exactly the case
// lib/db.ts's header says must use getTenantDb(tenantId) instead. Before
// this fix, EVERY tenant-isolation guarantee for this entire CSV import
// path rested solely on csv-parser.ts's manual `tenantId` filtering on each
// individual query — correct today, but with zero structural backstop if a
// future edit to that file ever missed one. getTenantDb(tenantId)'s Prisma
// Client Extension now auto-injects/re-asserts tenantId on every
// tenant-scoped model operation — including inside the `$transaction`
// callback csv-parser.ts opens per row, since the extension is preserved
// through `$transaction` (confirmed via lib/db.ts's own category-5 note:
// the extended transaction client's type is deliberately NOT
// `Prisma.TransactionClient`-compatible, specifically because it carries
// the extension). This closes the gap without changing any of
// csv-parser.ts's existing per-row logic.
import { getTenantDb } from "@/lib/db";
import { commitCsvImport, DECIMAL_STRING_REGEX, STRICT_DATE_REGEX } from "@/lib/inventory/csv-parser";
import {
  assertTenantWritable,
  SubscriptionLockedError,
  subscriptionLockedResponse,
} from "@/lib/auth/tenant";
import {
  assertRolePermission,
  ForbiddenRoleError,
  forbiddenRoleResponse,
} from "@/lib/auth/role-matrix";
import { z } from "zod";
// [v4.7] The receiving gateway's schemas — ONE receipt per import FILE.
import { purchaseDateSchema, supplierNameSchema } from "@/lib/data/receipts";

const positiveDecimalSchema = z
  .union([z.string(), z.number()])
  .transform((v) => String(v).trim())
  .refine((v) => DECIMAL_STRING_REGEX.test(v) && Number(v) > 0, {
    message: "يجب أن يكون رقماً موجباً أكبر من الصفر",
  });

const nonNegativeDecimalSchema = z
  .union([z.string(), z.number()])
  .transform((v) => String(v).trim())
  .refine((v) => DECIMAL_STRING_REGEX.test(v) && Number(v) >= 0, {
    message: "يجب أن يكون رقماً غير سالب (صفر أو أكثر)",
  });

// [FIX #2 — defensive] A frontend that omits an optional field by sending
// an empty string ("") rather than truly dropping the key from the JSON
// body is a common pattern (e.g. a controlled <input> bound to "" by
// default). Without this normalization, "" reaches STRICT_DATE_REGEX,
// fails it, and the ENTIRE commit request is rejected with 400 — even
// though every other row in the same payload is perfectly valid and the
// merchant's intent was clearly "no expiry date for this row." Empty
// string is treated identically to an absent field: normalized to
// `undefined` BEFORE the date-shape regex ever sees it. A non-empty but
// malformed value (e.g. "31-12-2026") is still rejected with the same
// specific, actionable message as before — this only widens what counts
// as "field not provided," it does not loosen the format check itself.
const expiryDateSchema = z
  .string()
  .optional()
  .transform((v) => (v === "" ? undefined : v))
  .pipe(
    z
      .string()
      .regex(STRICT_DATE_REGEX, "تاريخ الانتهاء يجب أن يكون بالصيغة YYYY-MM-DD (مثال: 2026-12-31)")
      .refine((v) => !isNaN(new Date(v).getTime()), {
        message: "تاريخ الانتهاء غير صالح",
      })
      .optional()
  );

const newProductRowSchema = z
  .object({
    lineNumber: z.number(),
    // [v4.5] The row's full confirmed barcode set — zero, one, or many. This is
    // the authoritative field NewProductImportData declares (barcodes: [] is
    // the legitimate "this unit has no barcode yet" case). Each entry always
    // carries its own human-confirmed source.
    barcodes: z
      .array(
        z.object({
          barcode: z.string().trim().min(1, "قيمة الباركود مطلوبة"),
          // Never inferred from the value's digit pattern (T3a §5).
          barcodeSource: z.enum(["GS1", "INTERNAL"]),
        })
      )
      .optional()
      .default([]),
    // [DEPRECATED — INPUT SHIM, mirrors app/api/inventory/products/route.ts's
    // identical shim] A preview payload generated by a pre-v4.5 client (one
    // still served from T4a2's stale service-worker cache) sends the single
    // scalar pair instead of `barcodes`. Folded into `barcodes` by the
    // transform below, and ONLY when `barcodes` is empty. A scalar arriving
    // WITHOUT a source is rejected outright by the refine below rather than
    // stored unclassified — the source is never guessed, and never defaulted.
    barcode: z.string().optional().nullable(),
    barcodeSource: z.enum(["GS1", "INTERNAL"]).optional().nullable(),
    name: z.string().min(1, "اسم المنتج مطلوب"),
    category: z.string().optional(),
    unitName: z.string().min(1, "اسم الوحدة مطلوب"),
    // [FIX — reverted] conversionFactor is a plain positive decimal here,
    // NOT locked to 1 at the schema level. This array holds BOTH
    // "brand-new product" rows (whose unit must be the base unit, factor
    // 1) AND "additional packaging unit on an existing product" rows
    // (whose unit must NOT be factor 1) — csv-parser.ts's own preview/
    // commit logic documents this explicitly (see its "known, documented
    // limitation" note on newProductsCount). Which case a given row is
    // can only be determined at commit time, against the product's real
    // (name, category) match in the live DB — never knowable here at the
    // route/schema layer in isolation. The actual base-unit-vs-1 /
    // duplicate-factor rule is enforced correctly and authoritatively by
    // validatePackagingUnits() inside commitCsvImport(), against the
    // product's REAL current units — that is the single source of truth
    // for this rule, not a blanket schema-level check here, which would
    // (and previously did, in an earlier revision of this file) reject
    // every legitimate additional-unit CSV row outright.
    conversionFactor: positiveDecimalSchema,
    priceWholesale: positiveDecimalSchema,
    pricingCurrency: z.enum(["SYP", "USD"]).optional(),
    initialBatchNumber: z.string().optional(),
    initialQuantity: nonNegativeDecimalSchema.optional(),
    // [v4.4, T4g] Required for any row that creates a new ProductBatch.
    // Always SYP, always per the product's base unit — deliberately with no
    // pricingCurrency counterpart. Required (not optional) HERE because this
    // schema only ever sees the `newProducts` array: every row in it is by
    // definition a net-new-batch row (a pure price-update row travels in the
    // separate `priceUpdates` array below and never reaches this schema).
    // csv-parser.ts's per-row validation still owns the merchant-facing
    // "missing field" reporting, and names سعر التكلفة in the import report.
    costPrice: positiveDecimalSchema,
    batchNumber: z.string().optional(),
    quantity: nonNegativeDecimalSchema.optional(),
    expiryDate: expiryDateSchema,
  })
  .refine((data) => !!(data.initialBatchNumber || data.batchNumber), {
    message: "رقم الدفعة الأولى مطلوب",
    path: ["initialBatchNumber"],
  })
  .refine(
    (data) => data.initialQuantity !== undefined || data.quantity !== undefined,
    {
      message: "الكمية الأولية مطلوبة",
      path: ["initialQuantity"],
    }
  )
  // [v4.5] "A barcode value and its human-confirmed source always travel
  // together" (T3a §5) — enforced on the LEGACY scalar pair, which is the only
  // way an unclassified barcode could reach this route. The `barcodes` array
  // cannot express the violation at all: its element type REQUIRES the source.
  .refine(
    (data) => {
      const legacy = data.barcode?.trim();
      if (!legacy) return true;
      return data.barcodeSource === "GS1" || data.barcodeSource === "INTERNAL";
    },
    {
      message:
        "لم يُحدَّد مصدر الباركود (GS1 أو INTERNAL) لبعض الصفوف. يرجى إعادة رفع الملف ومعاينته ثم تأكيد الاستيراد من جديد — عمود barcodeSource إلزامي لأي صف يحمل باركود.",
      path: ["barcodeSource"],
    }
  )
  // [FIX #4 — compile error] The two .refine() calls above only VALIDATE at
  // runtime — Zod's type system can't narrow z.infer's output based on a
  // refine's boolean condition, so TypeScript still saw
  // initialBatchNumber/initialQuantity as optional even on a row that had
  // already passed both refines. That mismatched NewProductImportData's
  // actual shape (both fields required, non-optional) in csv-parser.ts,
  // which is what produced the "Type 'string | undefined' is not
  // assignable to type 'string'" error at the commitCsvImport(db, tenantId,
  // { newProducts, priceUpdates }) call site. This transform runs only
  // AFTER both refines have already passed, so the fallback here is
  // runtime-safe, not just a type-level assertion: it collapses each alias
  // pair into the single guaranteed field NewProductImportData expects,
  // producing an output type that matches it exactly instead of asking
  // TypeScript to trust a validation it structurally cannot see.
  //
  // [v4.5] The same transform now also collapses the legacy barcode scalar pair
  // into `barcodes`, which is what makes this route's output satisfying
  // NewProductImportData's `barcodes: ImportUnitBarcode[]` field.
  .transform((data) => {
    // [v4.5] Fold the legacy scalar pair into the authoritative list — ONLY
    // when the list itself is empty, so a modern payload is never modified.
    // Structurally incapable of producing an unclassified entry: the refine
    // above already rejected a scalar without a source, and the truthiness
    // check here is a second, local guard.
    const legacyValue = data.barcode?.trim();
    const barcodes =
      data.barcodes.length > 0
        ? data.barcodes
        : legacyValue && data.barcodeSource
          ? [{ barcode: legacyValue, barcodeSource: data.barcodeSource }]
          : [];

    return {
      ...data,
      barcodes,
      initialBatchNumber: (data.initialBatchNumber || data.batchNumber)!,
      initialQuantity: (data.initialQuantity ?? data.quantity)!,
    };
  });

const priceUpdateRowSchema = z.object({
  lineNumber: z.number(),
  barcode: z.string().min(1, "الباركود مطلوب لتحديث السعر"),
  productName: z.string(),
  unitName: z.string(),
  currentPriceWholesale: z.union([z.number(), z.string()]),
  newPriceWholesale: positiveDecimalSchema,
  pricingCurrency: z.enum(["SYP", "USD"]),
  unitId: z.string().min(1, "معرف الوحدة مطلوب"),
});

const commitImportSchema = z.object({
  newProducts: z.array(newProductRowSchema).default([]),
  priceUpdates: z.array(priceUpdateRowSchema).default([]),
  // [v4.7] ONE receipt per FILE (never a per-row column): the goods-receiving
  // date — a Damascus business day, required, never in the future — plus an
  // optional supplier, both picked on the upload screen.
  purchaseDate: purchaseDateSchema,
  supplierName: supplierNameSchema,
});

export async function POST(req: Request) {
  try {
    const session = await auth();
    if (!session || !session.user || !session.user.tenantId) {
      return NextResponse.json({ error: "UNAUTHORIZED", message: "يرجى تسجيل الدخول أولاً." }, { status: 401 });
    }

    // ADMIN-only: a bulk import is a catalog-wide operation, same reasoning
    // as manual product creation and the storefront toggle.
    assertRolePermission(session.user.role, "inventory:mutate");

    // Security boundary: check fresh subscription status in DB
    await assertTenantWritable(session.user.tenantId);

    const tenantId = session.user.tenantId;
    const body = await req.json();

    const validation = commitImportSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        {
          error: "VALIDATION_ERROR",
          message: validation.error.issues[0]?.message || "بيانات الاستيراد غير صالحة.",
        },
        { status: 400 }
      );
    }

    const { newProducts, priceUpdates, purchaseDate, supplierName } = validation.data;

    if (newProducts.length === 0 && priceUpdates.length === 0) {
      return NextResponse.json(
        { error: "NO_DATA", message: "لا توجد عناصر صالحة للاستيراد." },
        { status: 400 }
      );
    }

    // [FIX #3] Tenant-scoped client, not the raw one — see the import
    // comment above. NOT wrapped in an additional outer $transaction here:
    // commitCsvImport does not need one — each row's product/unit/batch
    // creation, and each price update, is already atomic on its own (see
    // that function's own docstring). Using getTenantDb(tenantId) instead
    // of the raw client makes each row's success or failure genuinely
    // independent AND tenant-safe by construction, not just by manual
    // discipline inside csv-parser.ts.
    const db = getTenantDb(tenantId);
    const result = await commitCsvImport(db, tenantId, {
      newProducts,
      priceUpdates,
      // [v4.7] The shared receipt parameters. commitCsvImport creates the
      // receipt inside the FIRST batch-creating row's transaction and reuses
      // it for later rows; a file that creates no batch creates no receipt.
      receipt: {
        userId: session.user.id,
        purchaseDate,
        supplierName,
      },
    });

    // [FIX #1 — critical] `skippedPriceUpdates` and `failedPriceUpdates` are
    // ARRAYS (see CommitCsvImportResult in csv-parser.ts), not counters.
    // The previous code compared `result.skippedPriceUpdates > 0` — an
    // array compared to a number. JS coerces the array via `.toString()`
    // (e.g. "[object Object],[object Object]" for 2+ entries, or the
    // stringified single object for exactly 1), then that string is
    // coerced to a number for `>`, which is always NaN. `NaN > 0` is
    // ALWAYS false. Net effect: `hasFailures` could never become true
    // because of a skipped price update, and the merchant-facing failure
    // message for skipped price updates could never be appended — an
    // import that silently skipped price-update rows (e.g. because the
    // row meant to create their target unit earlier in the same file had
    // itself failed) was reported back as a clean, fully-successful
    // import. Fixed by reading `.length` on both arrays, as already done
    // correctly for `failedNewProducts` and `failedPriceUpdates` elsewhere
    // in this same block.
    const hasFailures =
      result.failedNewProducts.length > 0 ||
      result.skippedPriceUpdates.length > 0 ||
      result.failedPriceUpdates.length > 0;

    const baseMessage = `تم تنفيذ الاستيراد: تم إنشاء ${result.createdProductsCount} منتج جديد وتحديث ${result.updatedPricesCount} سعر.`;
    const failureParts: string[] = [];
    if (result.failedNewProducts.length > 0) {
      failureParts.push(`تعذّر إنشاء ${result.failedNewProducts.length} منتج بسبب تعارض في الباركود`);
    }
    // [FIX #1, continued] `.length`, not the array itself.
    if (result.skippedPriceUpdates.length > 0) {
      failureParts.push(`تم تجاهل ${result.skippedPriceUpdates.length} تحديث سعر (الوحدة غير موجودة)`);
    }
    if (result.failedPriceUpdates.length > 0) {
      failureParts.push(`تعذّر تنفيذ ${result.failedPriceUpdates.length} تحديث سعر بسبب خطأ غير متوقع`);
    }
    const failureSuffix = failureParts.length > 0 ? ` ${failureParts.join("، ")} — راجع التفاصيل أدناه.` : "";

    return NextResponse.json({
      success: true,
      result,
      message: baseMessage + failureSuffix,
      hasFailures,
    });
  } catch (error) {
    if (error instanceof ForbiddenRoleError) {
      return forbiddenRoleResponse(error);
    }
    if (error instanceof SubscriptionLockedError) {
      return subscriptionLockedResponse(error);
    }
    console.error("Error executing CSV import commit:", error);
    return NextResponse.json({ error: "SERVER_ERROR", message: "حدث خطأ أثناء حفظ بيانات الاستيراد." }, { status: 500 });
  }
}